## Regression Assignment

## California Housing Dataset

## 1. Loading and Preprocessing

#### Step 1: Import Libraries

In [2]:
import pandas as pd
import numpy as np

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#### Step 2: Load the Dataset

In [3]:
housing = fetch_california_housing()

df = pd.DataFrame(housing.data, columns=housing.feature_names)
df["Price"] = housing.target

df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

#### Step 3: Understand the Dataset

In [21]:
df.info()

df.describe()

df.shape

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   Price       20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

#### Step 4: Check Missing Values

In [5]:
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Price         0
dtype: int64

Explanation: The California Housing dataset contains no missing values. Checking for missing values is important because missing data can reduce model accuracy and cause errors during training.

#### Step 5: Split Features and Target

In [9]:
X = df.drop("Price", axis=1)

y = df["Price"]

#### Step 6: Train-Test Split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

#### Step 7: Feature Scaling

In [8]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

Explanation: The dataset was converted into a pandas DataFrame for easier analysis. Missing values were checked, and none were found. The dataset was split into training and testing sets to evaluate model performance. Feature scaling using StandardScaler was applied because algorithms such as Support Vector Regression perform better when features are on the same scale.

## 2. Regression Algorithm Implementation

## Model 1 — Linear Regression

In [10]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train_scaled, y_train)

lr_pred = lr.predict(X_test_scaled)

How it works

Linear Regression predicts values by fitting the best straight line between input features and the target.

Why suitable

It is simple, fast, and works well when relationships are approximately linear.

## Model 2 — Decision Tree Regressor

In [11]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

How it works

Decision Trees split the dataset into smaller regions based on feature values.

Why suitable

It captures non-linear relationships and does not require feature scaling.

## Model 3 — Random Forest Regressor

In [12]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

How it works

Random Forest combines predictions from many Decision Trees.

Why suitable

It reduces overfitting and improves prediction accuracy.

## Model 4 — Gradient Boosting Regressor

In [13]:
from sklearn.ensemble import GradientBoostingRegressor

gb = GradientBoostingRegressor(random_state=42)

gb.fit(X_train, y_train)

gb_pred = gb.predict(X_test)

How it works

Gradient Boosting builds trees sequentially, where each new tree corrects the previous tree's errors.

Why suitable

It provides high prediction accuracy for structured datasets.

## Model 5 — Support Vector Regressor (SVR)

In [14]:
from sklearn.svm import SVR

svr = SVR()

svr.fit(X_train_scaled, y_train)

svr_pred = svr.predict(X_test_scaled)

How it works

SVR predicts values by finding the best margin around the data while minimizing prediction errors.

Why suitable

It works well for complex relationships and performs best after feature scaling.

## 3. Model Evaluation

### Import Metrics

In [15]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

### Create Evaluation Function

In [16]:
def evaluate(y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)

    return mse, mae, r2

### Evaluate All Models

In [17]:
models = {
    "Linear Regression": lr_pred,
    "Decision Tree": dt_pred,
    "Random Forest": rf_pred,
    "Gradient Boosting": gb_pred,
    "SVR": svr_pred
}

results = []

for name, pred in models.items():

    mse, mae, r2 = evaluate(y_test, pred)

    results.append([name, mse, mae, r2])

results_df = pd.DataFrame(
    results,
    columns=["Model", "MSE", "MAE", "R2 Score"]
)

results_df

               Model       MSE       MAE  R2 Score
0  Linear Regression  0.555892  0.533200  0.575788
1      Decision Tree  0.495235  0.454679  0.622076
2      Random Forest  0.255368  0.327543  0.805123
3  Gradient Boosting  0.293997  0.371643  0.775645
4                SVR  0.357004  0.398599  0.727563

Find Best Model

In [18]:
results_df.sort_values(by="R2 Score", ascending=False)

               Model       MSE       MAE  R2 Score
2      Random Forest  0.255368  0.327543  0.805123
3  Gradient Boosting  0.293997  0.371643  0.775645
4                SVR  0.357004  0.398599  0.727563
1      Decision Tree  0.495235  0.454679  0.622076
0  Linear Regression  0.555892  0.533200  0.575788

The model with the highest R² score and lowest MAE and MSE is considered the best-performing model because it predicts house prices more accurately.

The model with the lowest R² score is considered the worst-performing model because it explains less variation in the data and produces larger prediction errors.

## Conclusion

Five regression algorithms were implemented and evaluated using the California Housing dataset. Based on Mean Squared Error (MSE), Mean Absolute Error (MAE), and R² Score, Random Forest Regressor achieved the best performance. Linear Regression showed the lowest performance because it assumes a linear relationship, whereas the housing dataset contains more complex patterns.